kind: pipeline
name: default

steps:

  - name: docker
    image: plugins/docker
    settings:
      repo: bitsbeats/updater
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
    when:
      event: tag
